# Generated by Django 4.0.6 on 2022-07-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_watchmovietest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchMovieTest',
        ),
    ]
