# Generated by Django 4.0.6 on 2022-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_delete_watchmovietest'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movie_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
