# Generated by Django 4.0.6 on 2022-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_watchlist_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movie_url',
            field=models.CharField(max_length=100),
        ),
    ]
