# Generated by Django 4.0.6 on 2022-07-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_watchlist_movie_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMovieTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('movie_id', models.CharField(max_length=50)),
                ('movie_title', models.CharField(max_length=50)),
                ('movie_notes', models.CharField(max_length=500)),
                ('movie_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'watch_movie_test',
            },
        ),
    ]
